{
 "title": "Kubernetes / Networking / Cluster",
 "tags": [
  "origin:kubernetes-mixin",
  "owner:team-turtles"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{app=\"cadvisor\"}, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Rate of Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "avg by (namespace) (\n    rate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "avg by (namespace) (\n    rate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_packets_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_packets_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_packets_dropped_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    },
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_packets_dropped_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n"
    }
   ]
  },
  {
   "title": "Average Rate of Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (namespace) (\n    rate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Rate of Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (namespace) (\n    rate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_bytes_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_packets_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_packets_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_receive_packets_dropped_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    rate(container_network_transmit_packets_dropped_total{cluster_id=\"$cluster\",namespace!=\"\"}[$__rate_interval])\n  * on (cluster_id,namespace,pod) group_left ()\n    topk by (cluster_id,namespace,pod) (\n      1,\n      max by (cluster_id,namespace,pod) (kube_pod_info{host_network=\"false\",cluster_id=\"$cluster\"})\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of TCP Retransmits out of all sent segments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(node_netstat_Tcp_RetransSegs{cluster_id=\"$cluster\"}[$__rate_interval]) / rate(node_netstat_Tcp_OutSegs{cluster_id=\"$cluster\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of TCP SYN Retransmits out of all retransmits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(node_netstat_TcpExt_TCPSynRetrans{cluster_id=\"$cluster\"}[$__rate_interval]) / rate(node_netstat_Tcp_RetransSegs{cluster_id=\"$cluster\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}